name: Day 2 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to where to deploy
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps: [run: echo 'Buildingâ‹¯']
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: [run: echo 'ğŸ‘·ğŸ½Testingâ‹¯']
  load-test:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      run: |
        echo 'ğŸ‘ŸTestingâ‹¯'
        echo sleep 1
    production:
      if: github.event.inputs.environment == 'Production'
      runs-on: ubuntu-latest
      needs: [test, load-test]
      steps: 
        run: |
          echo '1ï¸âƒ£Deployingâ‹¯'
          echo '2ï¸âƒ£Deployingâ‹¯'
          echo '3ï¸âƒ£Deployingâ‹¯'
          echo '4ï¸âƒ£Deployingâ‹¯'
          echo '5ï¸âƒ£Deployedâœ”ï¸'
