name: Day 2 1
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to where to deploy
        type: environment
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps: [run: echo 'ğŸ‘·ğŸ½Testingâ‹¯']
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      run: |
        echo 'ğŸ‘ŸTestingâ‹¯',
        echo sleep 1
