name: Github Actions demo
on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build:
    name: ğŸ› ï¸echo FTW!
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, ğŸŒworld!'
      - name: Run a multi-line script
        run: |+
          echo Add other actions to build,
          echo test, and deploy your project.
